version: 1.32.2
commit: '%.%.%'
files:
  README.md:
    - 'denoland/deno:%.%.%'
    - ARG DENO_VERSION=%.%.%
  alpine.dockerfile: ARG DENO_VERSION=%.%.%
  bin.dockerfile: ARG DENO_VERSION=%.%.%
  centos.dockerfile: ARG DENO_VERSION=%.%.%
  debian.dockerfile: ARG DENO_VERSION=%.%.%
  distroless.dockerfile: ARG DENO_VERSION=%.%.%
  example/Dockerfile: 'denoland/deno:%.%.%'
  ubuntu.dockerfile: ARG DENO_VERSION=%.%.%
