version: 1.46.0
commit: '%.%.%'
files:
  README.md:
    - 'denoland/deno:%.%.%'
    - 'denoland/deno:bin-%.%.%'
  alpine.dockerfile: ARG DENO_VERSION=%.%.%
  bin.dockerfile: ARG DENO_VERSION=%.%.%
  debian.dockerfile: ARG DENO_VERSION=%.%.%
  distroless.dockerfile: ARG DENO_VERSION=%.%.%
  example/Dockerfile: 'denoland/deno:%.%.%'
  ubuntu.dockerfile: ARG DENO_VERSION=%.%.%
