#!/bin/sh
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname $0); pwd)
HANDLER_NAME=$(echo "$_HANDLER" | cut -d. -f2)
HANDLER_FILE=$(echo "$_HANDLER" | cut -d. -f1)

echo "
import { $HANDLER_NAME } from '$LAMBDA_TASK_ROOT/$HANDLER_FILE.ts';
const API_ROOT =
  'http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/';
while (true) {
  const next = await fetch(API_ROOT + 'next');
  const reqId = next.headers.get('Lambda-Runtime-Aws-Request-Id');
  const body = await $HANDLER_NAME(await next.json());
  const res = await fetch(
    API_ROOT + reqId + '/response',
    {
      method: 'POST',
      body: JSON.stringify(body)
    }
  )
  await res.blob();
}
" > /tmp/runtime.js

# This assumes that you zipped up the DENO_DIR, see README.
cp -R $LAMBDA_TASK_ROOT/.deno_dir /tmp/deno_dir
mkdir -p /tmp/deno_dir/gen/file$LAMBDA_TASK_ROOT
mv /tmp/deno_dir/LAMBDA_TASK_ROOT/* /tmp/deno_dir/gen/file$LAMBDA_TASK_ROOT

DENO_DIR=/tmp/deno_dir $SCRIPT_DIR/amz-deno run --allow-net --allow-read /tmp/runtime.js
