name: set_docker_tags
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter version number to set the tags to.'
        type: string
        required: true

jobs:
  set_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Check if source image exists
        run: |
          docker manifest inspect denoland/deno:${{ github.event.inputs.version }} > /dev/null

      - name: Set tags to version
        run: |
          docker buildx imagetools create -t denoland/deno:latest denoland/deno:${{github.event.inputs.version}}
          docker buildx imagetools create -t denoland/deno:debian denoland/deno:${{github.event.inputs.version}}
          docker buildx imagetools create -t denoland/deno:alpine denoland/deno:alpine-${{github.event.inputs.version}}
          docker buildx imagetools create -t denoland/deno:bin denoland/deno:bin-${{github.event.inputs.version}}
          docker buildx imagetools create -t denoland/deno:distroless denoland/deno:distroless-${{github.event.inputs.version}}
          docker buildx imagetools create -t denoland/deno:ubuntu denoland/deno:ubuntu-${{github.event.inputs.version}}
